### ISSUE TITLE
@loadable/server在开发环境使用的问题

### ISSUE THREAD

**Issue by Pecking** [accforgit/blog-data#6]
请教一下,当你在开发环境使用@loadable/server在服务端读取script标签的时候,如果新建文件的时候,
你的loadable-stats.json 这个json文件时原来的文件,这不是预期结果你时怎么解决的?

**Comment by accforgit** [comment]
@Pecking 重新 run一遍

**Comment by Pecking** [comment]
如果在开发环境每次都执行这个操作,效率会很慢的,所以我被卡在这里了
