### ISSUE TITLE
componentDidMount

### ISSUE THREAD

**Issue by Pecking** [accforgit/blog-data#7]
测试了一下你的项目,当你页面在服务端渲染生成之后,在客户端还是执行了componentDidMount生命周期,这不是应该的,同样我也遇到了这个问题,我不知道该怎么做了?博主能一起解决嘛?
![image](https://user-images.githubusercontent.com/27414779/55927399-84165400-5c47-11e9-9060-ab6fdb325ef2.png)
![image](https://user-images.githubusercontent.com/27414779/55927402-8aa4cb80-5c47-11e9-8b9f-7cd11b730f29.png)

**Comment by accforgit** [comment]
@Pecking 客户端肯定会执行 componentDidMount的，这个一般情况下没什么问题，如果你不想在客户端还重复请求数据的话，多加个判断就行了，比如你需要在 componentDidMount中获取 this.data这个数据，那么再执行客户端componentDidMount获取数据之前判断下 this.data是不是已经拿到了，如果拿到了就不发请求即可

**Comment by Pecking** [comment]
@accforgit 是的,我之前理解错误了,我以为当我使用server render 的时候,我客户端不会执行componentDidMount

**Comment by Pecking** [comment]
Thanks, my loadData is asynchronous and related to redux-saga, I need to ensure that some asynchronous operations are performed before the render, but I don't know how to ensure that these asynchronous operations are completed, I tried using task.isRunning but He is always true, I don't know how to do it, I want to get help.
@accforgit
